# Plugins are rather limited in Github Pages, though a lot of useful ones are supported, check out:
# https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins
plugins:
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-redirect-from

title: Safing Docs
encoding: "utf-8"
lang: "en"
email: hello@safing.io
emailobfuscated: "=b!isfg>#nbjmup;ifmmpAtbgjoh/jp#?ifmmpAtbgjoh/jp=0b?"
description: > # this means to ignore newlines until "base_url:"
  Documentation for Safing Portmaster
base_url: "/" # the subpath of your site, e.g. /blog

### heavy externally referenced URLs
portmaster_settings_url: /portmaster/settings # Check reference in _data/menus.yml!
portmaster_api_url: /portmaster/api  # Check reference in _data/menus.yml!
coc_url: /community/code-of-conduct

### assets
assets_url: /assets/
img_url: /assets/img/
vendor_url: /vendor/

### external
account_server_url: https://account.safing.io/
assets_server_url: https://assets.safing.io/
company_agreement_url: https://www.firmenmonitor.at/Secure/CompanyDetail.aspx?CID=761761
download_linux_deb_url: https://updates.safing.io/latest/linux_amd64/packages/portmaster-installer.deb
download_linux_rpm_url: https://updates.safing.io/latest/linux_amd64/packages/portmaster-installer.rpm
download_linux_arch_url: https://updates.safing.io/latest/linux_amd64/packages/portmaster-installer.pkg.tar.xz
download_windows_url: https://updates.safing.io/latest/windows_amd64/packages/portmaster-installer.exe
github_url: https://github.com/safing

github_pm_url: https://github.com/safing/portmaster
github_pm_ui_url: https://github.com/safing/portmaster-ui
github_pm_packaging_url: https://github.com/safing/portmaster-packaging
github_docs_url: https://github.com/safing/docs
github_web_url: https://github.com/safing/web

github_suggest_feature_url: /issues/new?assignees=&labels=suggestion&template=suggest-feature.md
github_report_bug_url: /issues/new?assignees=&labels=bug&template=report-bug.md
github_report_compatibility_url: /issues/new?assignees=&labels=in/compatibility&template=report-compatibility.md

invidious_channel_url: https://invidio.us/channel/UC_6TW053IlS4M22g7CxnukA
kickstarter_url: https://www.kickstarter.com/projects/safingio/spn
reddit_url: https://reddit.com/r/safing
twitter_url: https://twitter.com/SafingIO
youtube_channel_url: https://www.youtube.com/channel/UC_6TW053IlS4M22g7CxnukA

### website pages
website_url: https://safing.io/
about_url: https://safing.io/about/
blog_url: https://safing.io/blog/
backlog_url: https://safing.io/backlog/
community_hub_url: https://safing.io/community-hub/
contact_url: https://safing.io/contact/
esa_bic_url: https://safing.io/esa-bic/
help_url: https://safing.io/support/
newsletter_url: https://safing.io/newsletter/
ownership_url: https://safing.io/ownership/
business_model_url: https://safing.io/business-model/
podcast_url: https://safing.io/podcast/
jobs_url: https://safing.io/jobs/
portmaster_url: https://safing.io/portmaster/
privacy_url: https://safing.io/privacy/
next_page_url: https://safing.io/next/
spn_url: https://safing.io/spn/
team_url: https://safing.io/team/
terms_url: https://safing.io/terms/
video_url: https://safing.io/video/
whitepaper_url: https://safing.io/files/whitepaper/Gate17.pdf
vpn_comparison_url: https://safing.io/blog/2020/01/22/how-the-spn-compares-to-vpns/
tor_comparison_url: https://safing.io/blog/2020/01/22/how-the-spn-compares-to-tor/
pihole_comparison_url: https://safing.io/blog/2021/12/09/portmaster-vs-pi-hole/
podcast_feed_url: https://safing.io/podcast.xml
blog_feed_url: https://safing.io/blog.xml

url: "https://docs.safing.io" # the base hostname & protocol for your site
github_ref_base_url: "https://github.com/safing"
godoc_ref_base_url: "https://pkg.go.dev/github.com/safing"

# Build settings
markdown: kramdown
# theme: minima
# plugins:
#   - jekyll-feed

# Header anchors
before_heading: true
anchor_class: header-anchor
anchor_body: "<img src=\"/assets/img/icons/link.svg\">"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .bundle/
