# to start the server just run
# docker-compose up

version: '3'
services:
  jekyll:
    image: jekyll/jekyll:4.2.2
    build:
      context: .
      dockerfile: Dockerfile
    command: jekyll serve -P 3000 --watch --incremental --livereload
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      - ./docker-compose.yml:/var/jekyll/connected
