core/apiKeys:
  hide_default: true
  manual: |
    API Keys need to be provided as a HTTP Basic or Bearer Authentication Header.  
    Usage of API Keys is only needed if you want to grant 3rd party software access to the Portmaster, or if you want to remotely manage the Portmaster via a Webbrowser.
    Be reminded that you are fully responsible yourself for the security and all implications of remote access.  
    On Linux, you can generate a new API Key like this: `echo "$(tr -dc A-Za-z0-9 </dev/urandom | head -c 50)?read=user&write=user"`

core/automaticUpdates:
  manual: |
    Currently, updates are checked for every hour. This frequency was chosen to stay up to date with the ever-changing landscape of malware/tracker/phishing domains managed by the various filter lists.

core/devMode:
  manual: |
    Never enable this in production, as anything will be able to fully control the Portmaster.

core/enableProcessDetection:
  manual: |
    Do not disable except for debugging purposes.

core/expertiseLevel:
  manual: |
    Relevant settings on this page are marked with <span class="setting-badge advanced">Advanced</span> and <span class="setting-badge developer">Developer</span> accordingly.

core/listenAddress:
  manual: |
    If you intend to access the Portmaster UI remotely, you can set this to `0.0.0.0:817`. [API Keys](#core/apiKeys) can be configured for access authentication. In addition to that, you will need to enable incoming connections in the Portmaster's own App Settings. Be reminded that you are fully responsible yourself for the security and all implications of remote access.

core/log/level:
  manual: |
    Log output with levels `trace`, `debug` and `info` contain a considerable amount of network information; such as processes, domains and IP addresses. If you are concerned about privacy in your log files, please use levels `warning`, `error` or `critical`.

core/metrics/instance:
  hide_default: true
  manual: |
    See the [prometheus label docs](https://prometheus.io/docs/practices/naming/#labels) for more information. The key used for the label is `instance`.

core/metrics/push:
  hide_default: true
  manual: |
    See the [prometheus exposition format docs](https://prometheus.io/docs/instrumenting/exposition_formats/) for more information. The data is POST-ed to the configured URL.

core/networkService:
  manual: |
    This allows you to use the Portmaster as a network-wide privacy system, similar to a Pi-Hole. This possibility exists mainly for testing and is not officially supported. You are free to tinker around with it though.

core/releaseChannel:
  manual: |
    Though the Portmaster has not reached the v1.0 release, it already uses the final release channels. This means that "Stable" is the current baseline and "Beta" is more unstable.

core/releaseLevel:
  manual: |
    Settings on this page are marked with <span class="setting-badge beta">Beta</span> and <span class="setting-badge experimental">Experimental</span> accordingly.

core/useSystemNotifications:
  manual: |
    You can [read more on the Portmaster Notifier](/portmaster/architecture/notifier) for additional information.

dns/dontResolveSpecialDomains:
  manual: |
    [Look at the dns querying deep dive](/portmaster/architecture/core-service/secure-dns#querying-deep-dive) for more information.

dns/listenAddress:
  manual: |
    `localhost` is a special value, which will make the Portmaster listen on both `127.0.0.1:53` and `::1`.  

    The shown default value `localhost:53` is used on Linux. The default for Windows is `0.0.0.0:53`, since on Windows requests are redirected to the same interface, not the loopback device.

dns/nameserverRetryRate:
  manual: |
    The Portmaster keeps track of the availablity of configured DNS servers. If requests to a server fail too often, it will be marked as failed and the Portmaster will stop sending requests to it for the duration set by this setting.

dns/nameservers:
  hide_help: true
  manual: |
    If you prefer to use other DNS servers than the pre-configured ones, you can configure them here. [See our guide on DNS Server Configuration](/portmaster/guides/dns-configuration) for extended details.

dns/noAssignedNameservers:
  manual: |
    This does not affect a special set of domains for testing connectivity.
    [Look at the dns querying deep dive](/portmaster/architecture/core-service/secure-dns#querying-deep-dive) for more information.

dns/noInsecureProtocols:
  manual: |
    This effectively disables mDNS as well as any DNS Server configured in your system or network.  
    This does not affect a special set of domains for testing connectivity.
    [Look at the dns querying deep dive](/portmaster/architecture/core-service/secure-dns#querying-deep-dive) for more information.

dns/noMulticastDNS:
  manual: |
    Queries for mDNS Domains such as `.local` will be sent to a System/Network DNS Server instead.
    [Look at the dns querying deep dive](/portmaster/architecture/core-service/secure-dns#querying-deep-dive) for more information.

filter/askTimeout:
  manual: |
    Regardless of the timeout configured here, the Portmaster will block the connection after a short timeout in order to keep a clean state and report the connection to the UI. Applications waiting for a prompt may report that they were not able to connect. In this case just ask the application to reconnect after handling the prompt.

filter/askWithSystemNotifications:
  manual: |
    Requires enabled [Desktop Notifications](#core/useSystemNotifications).

filter/blockInbound:
  layered: true
  manual: |
    In order to accept incoming connections, they must also be allowed by the [Incoming Rules](#filter/serviceEndpoints).

filter/blockInternet:
  layered: true
  manual: |
    You can use this setting to completely lock out an application from the Internet. Alternatively, you can block access globally while allowing specific apps as an exception in their respective per-app settings.

filter/blockLAN:
  layered: true
  manual: |
    You can use this setting to completely lock out an application from your local network. Alternatively, you can block access globally while allowing specific apps as an exception in their respective per-app settings.

filter/blockLocal:
  layered: true
  manual: |
    Internal connections on your device are usually not a threat. There are however cases where it makes sense to restrict localhost communication, such as for Browsers, if not needed.

filter/blockP2P:
  layered: true
  manual: |
    This setting is set to "Danger" by default because there is lots of software that directly communicates with IPs.
    
    If P2P connections are not needed widely, we recommend setting this to "Trusted" to greatly increase security. For exceptions in that case you can easily allow P2P connections for specific apps in their respective per-app setting.

filter/defaultAction:
  layered: true
  manual: |
    If set to "Prompt", the Portmaster will prompt you in the User Interface as well as via [Desktop Notifications](#core/useSystemNotifications) ([if enabled](#filter/askWithSystemNotifications)) to make a decision about a connection. You can also allow or block prompts in bulk in the UI.

filter/disableAutoPermit:
  layered: true
  manual: |
    This setting is meant to reduce noise when using [prompting](#filter/defaultAction). Currently, this feature is still rather primitive - comparing paths and names - but will become smarter in the future.  
    Auto allowing is disabled by default because it is a convenience and not a privacy feature.

filter/domainHeuristics:
  layered: true
  manual: |
    If this setting blocks benign connections, you can turn it off for single applications, but we highly recommend you leave it on globally. Domains generated by malware are an easy way to evade blocklists and slip through security systems.

filter/enable:
  manual: |
    Turning this off will completely disable the privacy filter and allow any connection. You should never use this in production. Instead, consider changing the [default action](#filter/defaultAction) to "Allow".

filter/endpoints:
  layered: true
  hide_default: true

filter/includeCNAMEs:
  layered: true
  manual: |
    This is used to block the new "unblockable" trackers that use a first-party subdomain CNAME'd (alias'd) to the tracking company.

filter/includeSubdomains:
  layered: true
  manual: |
    This makes it easier to block trackers that change their subdomain often in an attempt to avoid being caught by filter lists.

filter/lists:
  layered: true
  hide_default: true
  hide_help: true
  manual: |
    In the Portmaster UI you can easily select lists you want to activate.
    The filter lists are gathered and merged by us in order to be able to send hourly incremental updates. You can [view all lists the Portmaster subscribes to here](https://github.com/safing/intel-data).

filter/permanentVerdicts:
  manual: |
    Do not disable except for debugging purposes.

filter/preventBypassing:
  layered: true
  manual: |
    This is primarily to prevent software that plays nice from circumventing the Portmaster. While we will do it where it makes sense, this is not geared towards malware that is specifically made for circumenventing protection.

filter/removeBlockedDNS:
  layered: true
  manual: |
    Should a DNS response contain multiple IP addresses, and some of them would not be allowed to be connected to, the Portmaster will remove these answers in order to make it more likely for a connection to succeed within the permitted parameters.

filter/removeOutOfScopeDNS:
  layered: true
  manual: |
    [DNS Rebinding attacks](https://en.wikipedia.org/wiki/DNS_rebinding) allow an attacker to circumvent security policies. This feature blocks DNS Rebinding attacks on local systems.

filter/serviceEndpoints:
  layered: true
  manual: |
    If you need to accept incoming connections, try to narrow down from where you need to accept connections. A great way to start is to only accept connections from an organization via its AS number ([find it here](https://bgpview.io/)) or to only accept connections from specific countries.
    While potentially dangerous, you can allow any incoming connection by adding `+ *` to the [Incoming Rules](#filter/serviceEndpoints).

spn/dnsExitPolicy:

spn/enable:

spn/exitHubPolicy:
  layered: true

spn/homePolicy:
  layered: true

spn/routingAlgorithm:
  layered: true

spn/specialAccessCode:

spn/usagePolicy:
  layered: true

spn/use:
  layered: true
